// Contract §5: the other 22 E3 cases must instrument + compile + run, and stdout must equal the same
// (uninstrumented) program compiled natively with g++. A live local g++ is used when installed;
// otherwise the checked-in outputs in expected/e3 (generated by gen_expected.mjs with that g++).
import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadNodeEngine } from "./node_driver.mjs";
import { e3Cases } from "./e3_cases.mjs";
import { gxxRun, gxxVersion } from "./gxx.mjs";

const EXP = path.join(path.dirname(fileURLToPath(import.meta.url)), "expected", "e3");
const GXX = gxxVersion();
let eng;
before(async () => { eng = await loadNodeEngine(); console.log("# reference: " + (GXX ? "live " + GXX : "checked-in expected/e3 (" + JSON.parse(fs.readFileSync(path.join(EXP, "index.json"), "utf8")).compiler + ")")); });
after(() => eng && eng.dispose());

const cases = e3Cases();
test("there are exactly 22 E3 cases", () => assert.equal(cases.length, 22));

for (const c of cases) {
  test(`E3 ${c.id} ${c.name}: instrument+compile+run, stdout == g++`, async () => {
    const r = await eng.runProgram(c.source, c.stdin);
    assert.equal(r.ok, true, JSON.stringify(r.errors).slice(0, 1500));
    assert.equal(r.exit.reason, "exit", JSON.stringify(r.exit));
    assert.equal(r.instrumented, true);
    assert.ok(r.steps.length > 0);
    let expected;
    if (GXX) {
      const g = gxxRun(c.source, c.stdin);
      assert.ok(g.ok, g.log);
      expected = g.stdout;
      const saved = fs.readFileSync(path.join(EXP, c.id + ".txt"), "utf8");
      assert.equal(saved, expected, "checked-in expected output drifted from live g++");
    } else {
      expected = fs.readFileSync(path.join(EXP, c.id + ".txt"), "utf8");
    }
    assert.equal(r.stdout, expected);
    console.log(`# ${c.id} ${c.name}: steps=${r.steps.length} raw=${r.rawSteps} exit=${r.exit.code} stdout=${JSON.stringify(r.stdout).slice(0, 50)}`);
  });
}
